### ISSUE TITLE
Ethnicity study error

### ISSUE THREAD

**Issue by CarolineMorton** [opensafely/cohort-extractor#236] opened 2020-07-14 21:46 UTC
I have just tried to run the [ethnicity study](https://github.com/opensafely/ethnicity-covid-research) on the real data. I am getting this error (after quite a long time of running):

```
"app/cohortextractor/tpp_backend.py", line 1519, in assert_unique_ids
RuntimeError: Duplicate IDs found (1 rows)
```

It looks pretty self-explanatory but not sure how to fix from python.

**Comment by evansd** [comment] 2020-07-15 17:02
@CarolineMorton There are a lot of things going wrong here, but I think the root of the problem is actually with the diabetes algorithm here:
https://github.com/opensafely/ethnicity-covid-research/blob/38b387b6aeaa57d23d9427c859b8849b7b9f89f0/analysis/study_definition.py#L582-L595

Specifically, these two expressions fail with a division-by-zero error if `t2dm_count` is zero. 
```
(t1dm_count / t2dm_count) >= 2
(t1dm_count / t2dm_count) < 2
```
I would rewrite them as:
```
t1dm_count >= t2dm_count * 2
t1dm_count  < t2dm_count * 2
```

This error was obscured by various other problems, for which I'll create a separate ticket.

**Comment by evansd** [comment] 2020-07-15 17:28
I'm going to close this as I think this will solve the original problem, but feel free to re-open if needed.

**Closed by evansd** 2020-07-15 17:28 UTC
